### ISSUE TITLE
Seem to need pthread_join for output

### ISSUE THREAD

**Issue by ShaunSartin** [ShaunSartin/OS_Assignment4#8]
All Kerbals (threads) seem to wait for all previous kerbals before moving on.
Most likely culprit: pthread_join().
When deleted, kerbals stop printing messages.
Solution?

**Comment by KPham4588** [comment]
I thought that was the point? In class he said we just need to let everything run at least once, not necessarily the same amount of launches for each thread.

**Comment by ShaunSartin** [comment]
Maybe, I'll probably have to discuss this with him during his office hours tomorrow.
