### ISSUE TITLE
Error in professor's sample output?

### ISSUE THREAD

**Issue by ShaunSartin** [ShaunSartin/OS_Assignment4#9]
In the Programming Assignment 4 document the professor lists the following:

...
Kerbal 1: Assembles Engine 1, Fuselage, 2, Fuel Tank 1
Kerbal 2: Assembles Engine 2, Fuselage 1, Fuel Tank 2
...

Any explanation for this section of output?

**Comment by KPham4588** [comment]
Maybe it's typo.

**Comment by ShaunSartin** [comment]
After looking at it some more, I don't think this is a typo or a bug.
I think that the professor is assigning each part a specific number.
I believe that his output means:
Kerbal number1 grabs Engine number1, Fuselage number2, and Fuel Tank number1 
Kerbal number2 grabs Engine number2, Fuselage number1, and Fuel Tank number2 
This means that each kerbal only grabs one of each resource.
